/******************************************************************************/
/*           Generated by IBExpert 2025.11.17.1 20.11.2025 18:09:31           */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'C:\TestDb.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/*                                  Domains                                   */
/******************************************************************************/

CREATE DOMAIN D_DATE_CREATED AS
TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
NOT NULL;

CREATE DOMAIN D_EMAIL AS
VARCHAR(255)
CHECK (VALUE LIKE '%@%');

CREATE DOMAIN D_ID AS
INTEGER
NOT NULL;

CREATE DOMAIN D_NAME AS
VARCHAR(100);

CREATE DOMAIN D_PRICE AS
DECIMAL(10,2)
DEFAULT 0
CHECK (VALUE >= 0);



/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE GETCUSTOMERORDERS (
    CUSTIDINPUT D_ID)
RETURNS (
    ORDERID D_ID,
    PRODUCTNAME D_NAME,
    QUANTITY INTEGER,
    TOTALVALUE D_PRICE)
AS
BEGIN
  SUSPEND;
END^





SET TERM ; ^



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CUSTOMERS (
    CUSTOMERID  D_ID NOT NULL,
    NAME        D_NAME,
    EMAIL       D_EMAIL,
    CREATEDAT   D_DATE_CREATED
);

CREATE TABLE ORDERS (
    ORDERID     D_ID NOT NULL,
    CUSTOMERID  D_ID,
    PRODUCTID   D_ID,
    QUANTITY    INTEGER,
    ORDERDATE   D_DATE_CREATED
);

CREATE TABLE PRODUCTS (
    PRODUCTID  D_ID NOT NULL,
    NAME       D_NAME,
    PRICE      D_PRICE
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CUSTOMERS ADD PRIMARY KEY (CUSTOMERID);
ALTER TABLE ORDERS ADD PRIMARY KEY (ORDERID);
ALTER TABLE PRODUCTS ADD PRIMARY KEY (PRODUCTID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_PRODUCTS FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS (PRODUCTID);


/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE GETCUSTOMERORDERS (
    CUSTIDINPUT D_ID)
RETURNS (
    ORDERID D_ID,
    PRODUCTNAME D_NAME,
    QUANTITY INTEGER,
    TOTALVALUE D_PRICE)
AS
BEGIN
    FOR
        SELECT O.OrderId, P.Name, O.Quantity, (P.Price * O.Quantity)
        FROM Orders O
        JOIN Products P ON O.ProductId = P.ProductId
        WHERE O.CustomerId = :CustIdInput
        INTO :OrderId, :ProductName, :Quantity, :TotalValue
    DO
        SUSPEND;
END^




SET TERM ; ^

